services:
  ros2:
    image: itskalvik/blueos-ros2:0.0.4
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"

    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR

    volumes:
      - ./ros2_ws/:/home/ros2_ws/

    ports:
      - "4717:4717"
      - "88:88"
      - "8080:8080"
      - "9000:9000"

    #network_mode: host
    privileged: true
    tty: true
    stdin_open: true
