services:
  ros2:
    image: itskalvik/blueos-ros2:0.1.0
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"

    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR

    volumes:
      - ./ros2_ws/src/:/root/ros2_ws/src/

    ports:
      - "4717:4717"

    #network_mode: host
    privileged: true
    tty: true
    stdin_open: true
